[package]
name = "phosphor-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio", "tls-native-tls", "macros", "migrate", "uuid"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_plain = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
utoipa = { version = "4", features = ["actix_extras", "uuid"] }
utoipa-swagger-ui = "4"
gcloud-sdk = { version = "0.27.1", features = ["google-area120-tables-v1alpha1"] }
thiserror = "2.0.12"
serde_json = "1.0.140"
